# Generated by Django 4.2.11 on 2024-04-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('timeConcert', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=19, max_length=3)),
                ('nationalCode', models.IntegerField(max_length=10)),
                ('phoneNumber', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TimeConert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('numberOfSeats', models.IntegerField(null=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsale.concert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsale.location')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
                ('profileModel', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='ticketsale.profile')),
                ('timeModel', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='ticketsale.timeconert')),
            ],
        ),
    ]
