# Generated by Django 4.2.11 on 2024-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconert',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط'), (2, 'پایان'), (3, 'کنسل'), (4, 'کامل فروخته شده')], default='فروش بلیط'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationalCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
