# Generated by Django 4.2.11 on 2024-05-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0004_alter_timeconert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default=19, max_length=3),
        ),
    ]
