# Generated by Django 4.2.11 on 2024-06-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsale', '0006_alter_timeconert_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeConert',
            new_name='TimeConcert',
        ),
    ]
